# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shadow/Proyecto-Zoologico

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shadow/Proyecto-Zoologico

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shadow/Proyecto-Zoologico/CMakeFiles /home/shadow/Proyecto-Zoologico//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shadow/Proyecto-Zoologico/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Proyecto_Zoologuico

# Build rule for target.
Proyecto_Zoologuico: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Proyecto_Zoologuico
.PHONY : Proyecto_Zoologuico

# fast build rule for target.
Proyecto_Zoologuico/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/build
.PHONY : Proyecto_Zoologuico/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f lib/googleTest/googlemock/CMakeFiles/gmock.dir/build.make lib/googleTest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f lib/googleTest/googlemock/CMakeFiles/gmock_main.dir/build.make lib/googleTest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f lib/googleTest/googletest/CMakeFiles/gtest.dir/build.make lib/googleTest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f lib/googleTest/googletest/CMakeFiles/gtest_main.dir/build.make lib/googleTest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named Proyecto_Zoologuico_lib

# Build rule for target.
Proyecto_Zoologuico_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Proyecto_Zoologuico_lib
.PHONY : Proyecto_Zoologuico_lib

# fast build rule for target.
Proyecto_Zoologuico_lib/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Proyecto_Zoologuico_lib.dir/build.make src/CMakeFiles/Proyecto_Zoologuico_lib.dir/build
.PHONY : Proyecto_Zoologuico_lib/fast

#=============================================================================
# Target rules for targets named Proyecto_Zoologuico_exe

# Build rule for target.
Proyecto_Zoologuico_exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Proyecto_Zoologuico_exe
.PHONY : Proyecto_Zoologuico_exe

# fast build rule for target.
Proyecto_Zoologuico_exe/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Proyecto_Zoologuico_exe.dir/build.make src/CMakeFiles/Proyecto_Zoologuico_exe.dir/build
.PHONY : Proyecto_Zoologuico_exe/fast

Acuatico.o: Acuatico.cpp.o
.PHONY : Acuatico.o

# target to build an object file
Acuatico.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/Acuatico.cpp.o
.PHONY : Acuatico.cpp.o

Acuatico.i: Acuatico.cpp.i
.PHONY : Acuatico.i

# target to preprocess a source file
Acuatico.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/Acuatico.cpp.i
.PHONY : Acuatico.cpp.i

Acuatico.s: Acuatico.cpp.s
.PHONY : Acuatico.s

# target to generate assembly for a file
Acuatico.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/Acuatico.cpp.s
.PHONY : Acuatico.cpp.s

Animal.o: Animal.cpp.o
.PHONY : Animal.o

# target to build an object file
Animal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/Animal.cpp.o
.PHONY : Animal.cpp.o

Animal.i: Animal.cpp.i
.PHONY : Animal.i

# target to preprocess a source file
Animal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/Animal.cpp.i
.PHONY : Animal.cpp.i

Animal.s: Animal.cpp.s
.PHONY : Animal.s

# target to generate assembly for a file
Animal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/Animal.cpp.s
.PHONY : Animal.cpp.s

Habitad.o: Habitad.cpp.o
.PHONY : Habitad.o

# target to build an object file
Habitad.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/Habitad.cpp.o
.PHONY : Habitad.cpp.o

Habitad.i: Habitad.cpp.i
.PHONY : Habitad.i

# target to preprocess a source file
Habitad.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/Habitad.cpp.i
.PHONY : Habitad.cpp.i

Habitad.s: Habitad.cpp.s
.PHONY : Habitad.s

# target to generate assembly for a file
Habitad.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/Habitad.cpp.s
.PHONY : Habitad.cpp.s

SemiAcuatico.o: SemiAcuatico.cpp.o
.PHONY : SemiAcuatico.o

# target to build an object file
SemiAcuatico.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/SemiAcuatico.cpp.o
.PHONY : SemiAcuatico.cpp.o

SemiAcuatico.i: SemiAcuatico.cpp.i
.PHONY : SemiAcuatico.i

# target to preprocess a source file
SemiAcuatico.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/SemiAcuatico.cpp.i
.PHONY : SemiAcuatico.cpp.i

SemiAcuatico.s: SemiAcuatico.cpp.s
.PHONY : SemiAcuatico.s

# target to generate assembly for a file
SemiAcuatico.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/SemiAcuatico.cpp.s
.PHONY : SemiAcuatico.cpp.s

Terrestre.o: Terrestre.cpp.o
.PHONY : Terrestre.o

# target to build an object file
Terrestre.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/Terrestre.cpp.o
.PHONY : Terrestre.cpp.o

Terrestre.i: Terrestre.cpp.i
.PHONY : Terrestre.i

# target to preprocess a source file
Terrestre.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/Terrestre.cpp.i
.PHONY : Terrestre.cpp.i

Terrestre.s: Terrestre.cpp.s
.PHONY : Terrestre.s

# target to generate assembly for a file
Terrestre.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/Terrestre.cpp.s
.PHONY : Terrestre.cpp.s

Volador.o: Volador.cpp.o
.PHONY : Volador.o

# target to build an object file
Volador.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/Volador.cpp.o
.PHONY : Volador.cpp.o

Volador.i: Volador.cpp.i
.PHONY : Volador.i

# target to preprocess a source file
Volador.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/Volador.cpp.i
.PHONY : Volador.cpp.i

Volador.s: Volador.cpp.s
.PHONY : Volador.s

# target to generate assembly for a file
Volador.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/Volador.cpp.s
.PHONY : Volador.cpp.s

Zoologico.o: Zoologico.cpp.o
.PHONY : Zoologico.o

# target to build an object file
Zoologico.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/Zoologico.cpp.o
.PHONY : Zoologico.cpp.o

Zoologico.i: Zoologico.cpp.i
.PHONY : Zoologico.i

# target to preprocess a source file
Zoologico.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/Zoologico.cpp.i
.PHONY : Zoologico.cpp.i

Zoologico.s: Zoologico.cpp.s
.PHONY : Zoologico.s

# target to generate assembly for a file
Zoologico.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/Zoologico.cpp.s
.PHONY : Zoologico.cpp.s

criadero.o: criadero.cpp.o
.PHONY : criadero.o

# target to build an object file
criadero.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/criadero.cpp.o
.PHONY : criadero.cpp.o

criadero.i: criadero.cpp.i
.PHONY : criadero.i

# target to preprocess a source file
criadero.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/criadero.cpp.i
.PHONY : criadero.cpp.i

criadero.s: criadero.cpp.s
.PHONY : criadero.s

# target to generate assembly for a file
criadero.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/criadero.cpp.s
.PHONY : criadero.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/main.cpp.s
.PHONY : main.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proyecto_Zoologuico.dir/build.make CMakeFiles/Proyecto_Zoologuico.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Proyecto_Zoologuico"
	@echo "... Proyecto_Zoologuico_exe"
	@echo "... Proyecto_Zoologuico_lib"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... Acuatico.o"
	@echo "... Acuatico.i"
	@echo "... Acuatico.s"
	@echo "... Animal.o"
	@echo "... Animal.i"
	@echo "... Animal.s"
	@echo "... Habitad.o"
	@echo "... Habitad.i"
	@echo "... Habitad.s"
	@echo "... SemiAcuatico.o"
	@echo "... SemiAcuatico.i"
	@echo "... SemiAcuatico.s"
	@echo "... Terrestre.o"
	@echo "... Terrestre.i"
	@echo "... Terrestre.s"
	@echo "... Volador.o"
	@echo "... Volador.i"
	@echo "... Volador.s"
	@echo "... Zoologico.o"
	@echo "... Zoologico.i"
	@echo "... Zoologico.s"
	@echo "... criadero.o"
	@echo "... criadero.i"
	@echo "... criadero.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

